# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/drkey/v1/drkey.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/drkey/v1/drkey.proto\x12\x0eproto.drkey.v1*K\n\x08Protocol\x12 \n\x1cPROTOCOL_GENERIC_UNSPECIFIED\x10\x00\x12\x11\n\rPROTOCOL_SCMP\x10\x01\"\n\x08\x80\x80\x04\x10\xff\xff\xff\xff\x07\x42-Z+github.com/scionproto/scion/pkg/proto/drkeyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.drkey.v1.drkey_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/scionproto/scion/pkg/proto/drkey'
  _globals['_PROTOCOL']._serialized_start=46
  _globals['_PROTOCOL']._serialized_end=121
# @@protoc_insertion_point(module_scope)
