# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.daemon.v1 import daemon_pb2 as proto_dot_daemon_dot_v1_dot_daemon__pb2


class DaemonServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Paths = channel.unary_unary(
                '/proto.daemon.v1.DaemonService/Paths',
                request_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.PathsRequest.SerializeToString,
                response_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.PathsResponse.FromString,
                )
        self.AS = channel.unary_unary(
                '/proto.daemon.v1.DaemonService/AS',
                request_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.ASRequest.SerializeToString,
                response_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.ASResponse.FromString,
                )
        self.Interfaces = channel.unary_unary(
                '/proto.daemon.v1.DaemonService/Interfaces',
                request_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.InterfacesRequest.SerializeToString,
                response_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.InterfacesResponse.FromString,
                )
        self.Services = channel.unary_unary(
                '/proto.daemon.v1.DaemonService/Services',
                request_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.ServicesRequest.SerializeToString,
                response_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.ServicesResponse.FromString,
                )
        self.NotifyInterfaceDown = channel.unary_unary(
                '/proto.daemon.v1.DaemonService/NotifyInterfaceDown',
                request_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.NotifyInterfaceDownRequest.SerializeToString,
                response_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.NotifyInterfaceDownResponse.FromString,
                )
        self.DRKeyASHost = channel.unary_unary(
                '/proto.daemon.v1.DaemonService/DRKeyASHost',
                request_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyASHostRequest.SerializeToString,
                response_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyASHostResponse.FromString,
                )
        self.DRKeyHostAS = channel.unary_unary(
                '/proto.daemon.v1.DaemonService/DRKeyHostAS',
                request_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostASRequest.SerializeToString,
                response_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostASResponse.FromString,
                )
        self.DRKeyHostHost = channel.unary_unary(
                '/proto.daemon.v1.DaemonService/DRKeyHostHost',
                request_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostHostRequest.SerializeToString,
                response_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostHostResponse.FromString,
                )


class DaemonServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Paths(self, request, context):
        """Return a set of paths to the requested destination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AS(self, request, context):
        """Return information about an AS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interfaces(self, request, context):
        """Return the underlay addresses associated with
        the specified interfaces.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Services(self, request, context):
        """Return the underlay addresses associated with the
        specified services.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyInterfaceDown(self, request, context):
        """Inform the SCION Daemon of a revocation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DRKeyASHost(self, request, context):
        """DRKeyASHost returns a key that matches the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DRKeyHostAS(self, request, context):
        """DRKeyHostAS returns a key that matches the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DRKeyHostHost(self, request, context):
        """DRKeyHostHost returns a key that matches the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Paths': grpc.unary_unary_rpc_method_handler(
                    servicer.Paths,
                    request_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.PathsRequest.FromString,
                    response_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.PathsResponse.SerializeToString,
            ),
            'AS': grpc.unary_unary_rpc_method_handler(
                    servicer.AS,
                    request_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.ASRequest.FromString,
                    response_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.ASResponse.SerializeToString,
            ),
            'Interfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.Interfaces,
                    request_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.InterfacesRequest.FromString,
                    response_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.InterfacesResponse.SerializeToString,
            ),
            'Services': grpc.unary_unary_rpc_method_handler(
                    servicer.Services,
                    request_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.ServicesRequest.FromString,
                    response_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.ServicesResponse.SerializeToString,
            ),
            'NotifyInterfaceDown': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyInterfaceDown,
                    request_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.NotifyInterfaceDownRequest.FromString,
                    response_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.NotifyInterfaceDownResponse.SerializeToString,
            ),
            'DRKeyASHost': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeyASHost,
                    request_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyASHostRequest.FromString,
                    response_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyASHostResponse.SerializeToString,
            ),
            'DRKeyHostAS': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeyHostAS,
                    request_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostASRequest.FromString,
                    response_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostASResponse.SerializeToString,
            ),
            'DRKeyHostHost': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeyHostHost,
                    request_deserializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostHostRequest.FromString,
                    response_serializer=proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostHostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.daemon.v1.DaemonService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DaemonService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Paths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.daemon.v1.DaemonService/Paths',
            proto_dot_daemon_dot_v1_dot_daemon__pb2.PathsRequest.SerializeToString,
            proto_dot_daemon_dot_v1_dot_daemon__pb2.PathsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.daemon.v1.DaemonService/AS',
            proto_dot_daemon_dot_v1_dot_daemon__pb2.ASRequest.SerializeToString,
            proto_dot_daemon_dot_v1_dot_daemon__pb2.ASResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Interfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.daemon.v1.DaemonService/Interfaces',
            proto_dot_daemon_dot_v1_dot_daemon__pb2.InterfacesRequest.SerializeToString,
            proto_dot_daemon_dot_v1_dot_daemon__pb2.InterfacesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Services(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.daemon.v1.DaemonService/Services',
            proto_dot_daemon_dot_v1_dot_daemon__pb2.ServicesRequest.SerializeToString,
            proto_dot_daemon_dot_v1_dot_daemon__pb2.ServicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyInterfaceDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.daemon.v1.DaemonService/NotifyInterfaceDown',
            proto_dot_daemon_dot_v1_dot_daemon__pb2.NotifyInterfaceDownRequest.SerializeToString,
            proto_dot_daemon_dot_v1_dot_daemon__pb2.NotifyInterfaceDownResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DRKeyASHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.daemon.v1.DaemonService/DRKeyASHost',
            proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyASHostRequest.SerializeToString,
            proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyASHostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DRKeyHostAS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.daemon.v1.DaemonService/DRKeyHostAS',
            proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostASRequest.SerializeToString,
            proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostASResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DRKeyHostHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.daemon.v1.DaemonService/DRKeyHostHost',
            proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostHostRequest.SerializeToString,
            proto_dot_daemon_dot_v1_dot_daemon__pb2.DRKeyHostHostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
